name: .NET

on:
  push:
    branches: [ master ]
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
    - "[0-9]+.[0-9]+.[0-9]+-.*"
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
      
    - name: Finding files to Push
      id: finding-files
      if: startsWith(github.event_name, 'refs/tags/v')
      run: |
        echo "::set-output name=FILELIST::$(find . -name 'bin/*.nupkg' -print)"             
    - name: Push
      if: startsWith(github.event_name, 'refs/tags/v')
      run: |
        IFS="," read -a myarray <<< ${{ steps.finding-files.outputs.FILELIST }}
        for i in "${myarray[@]}"; do
          dotnet nuget push "${i}" --source https://nuget.pkg.github.com/tomaszmalik/index.json --api-key ${GITHUB_TOKEN}
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
